baseURL = 'https://protocolobase.com.br/'
locale = 'pt-br'
title = 'Protocolo Base'
theme = 'PaperMod'
googleAnalytics = "G-TB1PR5T4BV"

[params]
  env = "production"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
  identifier = "privacidade"
  name = "Política de Privacidade"
  url = "/politica-de-privacidade/"
  weight = 10