name: Deploy Matinal Automatizado (CRON)

on:
  workflow_dispatch: # Mantém apenas a ativação manual de emergência

jobs:
  trigger-build:
    name: Aciona API da Cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Dispara o Webhook de Deploy
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"